### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by YujiaCheng1996** [o0oo0ooo0/EUserv_extend#1]
希望增加server酱等推送结果功能。

**Comment by o0oo0ooo0** [comment]
好的,准备加上

**Comment by o0oo0ooo0** [comment]
server酱推送添加好了

**Comment by YujiaCheng1996** [comment]
感谢，大佬能不能改一下，续费失败才推送，要不标题体现下成功或者失败也行，无需续费就不用推送了，设定每天执行一次简直是信息轰炸。

**Comment by o0oo0ooo0** [comment]
触发周期可以选择 每个月的几号触发,就不会有这么多通知了,cron表达式可以参考
https://cloud.tencent.com/document/product/583/9708

YujiaCheng1996 <notifications@github.com> 于2020年12月14日周一 下午10:24写道：

**Comment by o0oo0ooo0** [comment]
> 感谢，大佬能不能改一下，续费失败才推送，要不标题体现下成功或者失败也行，无需续费就不用推送了，设定每天执行一次简直是信息轰炸。

触发周期可以选择 每个月的几号触发,就不会有这么多通知了,cron表达式可以参考cloud.tencent.com/document/product/583/9708

**Comment by YujiaCheng1996** [comment]
自己fork后小改了一下
