### ISSUE TITLE
调用失败

### ISSUE THREAD

**Issue by ttt789-ppo** [o0oo0ooo0/EUserv_extend#11]
我全部都照教程弄的，上传了层的zip，把main.py修改并粘贴到函数编辑区，环境都是python3.6，也绑定了层，但测试了就是调用失败，也没推送，这是怎么回事？

**Comment by ttt789-ppo** [comment]
换成香港就好了，不过里面的server酱和pushplus的调用接口该换新的了，server酱https://sctapi.ftqq.com/SENDKEY.send
，pushplus的接口http://www.pushplus.plus/send
，这两个我都是换了之后才推送的

**Comment by o0oo0ooo0** [comment]
> 换成香港就好了，不过里面的server酱和pushplus的调用接口该换新的了，server酱https://sctapi.ftqq.com/SENDKEY.send
> ，pushplus的接口http://www.pushplus.plus/send
> ，这两个我都是换了之后才推送的

好的,server酱可能把旧版本关了,新版本现在无法~~白嫖~~
然后这个pushplus似乎有两个,所有你收不到推送,现在支持的是https://pushplus.hxtrip.com/message
