### ISSUE TITLE
登入失败

### ISSUE THREAD

**Issue by giszh86** [o0oo0ooo0/EUserv_extend#12]
我的账号密码明明是正确的，在官网也可以直接登入，但用这个就登入失败，不知道什么原因

**Comment by o0oo0ooo0** [comment]
图

**Comment by giszh86** [comment]
这个是我的配置

![image](https://user-images.githubusercontent.com/8955999/126765698-09775481-e550-4285-8f72-5405bd09c3c6.png)



这个是日志
![image](https://user-images.githubusercontent.com/8955999/126765631-7b2450e1-d64a-4731-8468-f907a628015b.png)

**Comment by o0oo0ooo0** [comment]
我是可以正常登录的,你重置密码试试看

**Comment by gs314520** [comment]
不是个例，登录失败已经有一个多星期了，之前没问题
![Screenshot](https://user-images.githubusercontent.com/77563575/126893545-00a7cc2d-283b-4ce9-b5d2-e2ccd09485fd.png)

**Comment by o0oo0ooo0** [comment]
> 不是个例，登录失败已经有一个多星期了，之前没问题
> ![Screenshot](https://user-images.githubusercontent.com/77563575/126893545-00a7cc2d-283b-4ce9-b5d2-e2ccd09485fd.png)
试试它的能不能登录https://github.com/CokeMine/EUserv_extend

**Comment by gs314520** [comment]
> > 不是个例，已经登录失败的有一个多礼拜了，之前没
> > 遇到问题能不能登录https://github.com/CokeMine/EUserv_extend
> > ![截屏](https://user-images.githubusercontent.com/77563575/126893545-00a7cc2d-283b-4ce9-b5d2-e2ccd09485fd.png)[](https://github.com/CokeMine/EUserv_extend)

把原来的函数删了重新搞了下好了
