### ISSUE TITLE
登入失败

### ISSUE THREAD

**Issue by siyue666** [o0oo0ooo0/EUserv_extend#14]
有点bug，有得账号回登入失败，看有人修复了，但是不知道怎么用云函数执行

**Comment by spiritLHL** [comment]
> 
> 
> 有点bug，有得账号回登入失败，看有人修复了，但是不知道怎么用云函数执行

https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC

**Comment by siyue666** [comment]
> > 有点bug，有得账号回登入失败，看有人修复了，但是不知道怎么用云函数执行
> 
> https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC

这些我知道，操作没问题，另一个账号可以续期一切正常，这个就直接登入失败

**Comment by spiritLHL** [comment]
> 
> 
> > > 有点bug，有得账号回登入失败，看有人修复了，但是不知道怎么用云函数执行
> > 
> > 
> > [https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC ](https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC)
> 
> 这些我知道，操作没问题，另一个账号可以续期一切正常，这个就直接登入失败

是不是账号被封了，看看邮箱

**Comment by siyue666** [comment]
> > > > 有点bug，有得账号回登入失败，看有人修复了，但是不知道怎么用云函数执行
> > > 
> > > 
> > > [https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC ](https://www.spiritlhl.top/54/#%E8%87%AA%E5%8A%A8%E7%BB%AD%E6%9C%9F%E7%9A%84%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E5%85%8D%E8%B4%B9%E8%84%9A%E6%9C%AC)
> > 
> > 
> > 这些我知道，操作没问题，另一个账号可以续期一切正常，这个就直接登入失败
> 
> 是不是账号被封了，看看邮箱

没有，自己手动登过了都是正常的，用了别人的服务器版本的续费成功了，但是不怎么会设置crontab，还是觉得云函数的方便

**Comment by spiritLHL** [comment]
> 没有，自己手动登过了都是正常的，用了别人的服务器版本的续费成功了，但是不怎么会设置crontab，还是觉得云函数的方便

来个仓库，我看看，可以改成云函数形式的

**Comment by siyue666** [comment]
> > 没有，自己手动登过了都是正常的，用了别人的服务器版本的续费成功了，但是不怎么会设置crontab，还是觉得云函数的方便
> 
> 来个仓库，我看看，可以改成云函数形式的

上传了，看我仓库

**Comment by spiritLHL** [comment]
> 上传了，看我仓库
你那个
if __name__ == '__main__':  
改成
def main_handler(event, context):
然后应该就能照常部署了

好像这个是

https://github.com/cokemine/EUserv_extend

这个仓库的脚本

**Comment by siyue666** [comment]
> > 上传了，看我仓库
> 
> 你那个
> if **name** == '**main**':
> 改成
> def main_handler(event, context):
> 然后应该就能照常部署了
> 
> 好像这个是
> 
> https://github.com/cokemine/EUserv_extend
> 
> 这个仓库的脚本

成功了，非常感谢大佬🙏
