### ISSUE TITLE
再次出现登录失败

### ISSUE THREAD

**Issue by ChirmyRam** [o0oo0ooo0/EUserv_extend#16]
貌似是德鸡官方改了登录入口，加了验证码。

**Comment by o0oo0ooo0** [comment]
似乎真的登不了了,上游被GitHub关了,我没地嫖代码了

**Comment by weilongf** [comment]
难受

**Comment by nsfw404** [comment]
https://github.com/smg-cyber/EUserv_extend  请大佬继续抄，顺便问一下可不可以支持下go-cq的推送

**Comment by ChirmyRam** [comment]
> https://github.com/smg-cyber/EUserv_extend 请大佬继续抄，顺便问一下可不可以支持下go-cq的推送

抄这个仓库的脚本？从它的actions日志来看还是登录失败，这些脚本不都一样的失效。

**Comment by nsfw404** [comment]
啊这，那岂不是没得用了QAQ

**Comment by o0oo0ooo0** [comment]
> https://github.com/smg-cyber/EUserv_extend 请大佬继续抄，顺便问一下可不可以支持下go-cq的推送

看来只能放过 EUserv 了,go-cq 不是QQ机器人吗,也算推送服务吗,不过项目大概已经结束了 没支持的必要了.还有,别叫我大佬,我要是是大佬就不用抄了.

**Comment by guoqing1977** [comment]
我是EUserv 设置先开启2步验证 保存后 再取消 登出
梯子开个不常用地区全区 验证码就出来了 验证后脚本可以使用了

**Comment by weilongf** [comment]
> 我是EUserv 设置先开启2步验证 保存后 再取消 登出
> 梯子开个不常用地区全区 验证码就出来了 验证后脚本可以使用了

亲测有用！

**Comment by o0oo0ooo0** [comment]
> 我是EUserv 设置先开启2步验证 保存后 再取消 登出
> 梯子开个不常用地区全区 验证码就出来了 验证后脚本可以使用了

有效!
