### ISSUE TITLE
报错：unable to import bs4

### ISSUE THREAD

**Issue by shadowsocke** [o0oo0ooo0/EUserv_extend#7]
{
	"resource": "/usr/……/src/index.py",
	"owner": "python",
	"code": "import-error",
	"severity": 8,
	"message": "Unable to import 'bs4'",
	"source": "pylint",
	"startLineNumber": 5,
	"startColumn": 1,
	"endLineNumber": 5,
	"endColumn": 1
}

**Comment by o0oo0ooo0** [comment]
按步骤
