### ISSUE TITLE
报错，手动续费发现，多了几个步骤

### ISSUE THREAD

**Issue by MicroMatrixOrg** [o0oo0ooo0/EUserv_extend#8]
报错，手动续费发现，多了几个步骤，会跳出对话框，要求再次验证密码，不知道是不是只有我一个人这样

**Comment by o0oo0ooo0** [comment]
啥错啊

**Comment by MicroMatrixOrg** [comment]
> 啥错啊

就是一个续费失败的提示，显示登录失败，请检查登录信息。手动续费发现比之前多了几个验证的步骤

**Comment by zaxigia** [comment]
我也遇到了，全部登录失败

**Comment by if1y** [comment]
爬虫抓到的源码比实际访问要少了一部分，正好是用来判定登录状态和检索服务器信息的

**Comment by o0oo0ooo0** [comment]
上游修好了,可以嫖了...https://github.com/cokemine/EUserv_extend/commit/35f3326c032db4cc4ac43bbfb852f36f747249cf #

**Comment by MicroMatrixOrg** [comment]
> 上游修好了,可以嫖了...[cokemine/EUserv_extend@35f3326](https://github.com/cokemine/EUserv_extend/commit/35f3326c032db4cc4ac43bbfb852f36f747249cf) #

我看你也更新了，你是修改了成他的版本了吗 (^-^)

**Comment by o0oo0ooo0** [comment]
> > 上游修好了,可以嫖了...[cokemine/EUserv_extend@35f3326](https://github.com/cokemine/EUserv_extend/commit/35f3326c032db4cc4ac43bbfb852f36f747249cf) #
> 
> 我看你也更新了，你是修改了成他的版本了吗 (^-^)

抄过来了嘿嘿

**Comment by MicroMatrixOrg** [comment]
> > > 上游修好了,可以嫖了...[cokemine/EUserv_extend@35f3326](https://github.com/cokemine/EUserv_extend/commit/35f3326c032db4cc4ac43bbfb852f36f747249cf) #
> > 
> > 
> > 我看你也更新了，你是修改了成他的版本了吗 (^-^)
> 
> 抄过来了嘿嘿

大意了，我还把你的通知放到他的上面改了半天，还报错，我垃圾了

**Comment by if1y** [comment]
还是一样的问题，没有解决反爬

**Comment by o0oo0ooo0** [comment]
> 还是一样的问题，没有解决反爬

看看现在能用不,我上次没抄全..

**Comment by if1y** [comment]
> > 还是一样的问题，没有解决反爬
> 
> 看看现在能用不,我上次没抄全..

应该没问题，能正常爬取到了，感谢~
