### ISSUE TITLE
云函数部署新的代码测试提示登陆失败，请大佬看下，谢谢。

### ISSUE THREAD

**Issue by ella-tj** [o0oo0ooo0/EUserv_extend#9]
START RequestId:4c164263-ff1c-427b-913e-d8828ef60500

******************************

正在续费第 1 个账号

Starting new HTTPS connection (1): support.euserv.com:443

https://support.euserv.com:443 "GET /index.iphp HTTP/1.1" 302 3220

https://support.euserv.com:443 "GET /index.iphp?sess_id=26b73ee82fe17ff3b40574805879518610132301351626159590 HTTP/1.1" 200 3220

https://support.euserv.com:443 "GET /pic/logo_small.png HTTP/1.1" 200 78

Starting new HTTPS connection (1): support.euserv.com:443

/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

  InsecureRequestWarning)

https://support.euserv.com:443 "POST /index.iphp HTTP/1.1" 302 20

/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

  InsecureRequestWarning)

https://support.euserv.com:443 "GET /index.iphp HTTP/1.1" 302 3217

/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

  InsecureRequestWarning)

https://support.euserv.com:443 "GET /index.iphp?sess_id=11e1d2e919a5101f14dbd57a3c2d7647129226172871626159593 HTTP/1.1" 200 3217

第 1 个账号登陆失败，请检查登录信息

**Comment by o0oo0ooo0** [comment]
~~抄~~改好了,用最新版本

**Comment by ella-tj** [comment]
用的就是最新版本，还是出错

**Comment by o0oo0ooo0** [comment]
> 用的就是最新版本，还是出错

额,我也出错了,之前明明还能用的...试试他的https://github.com/cokemine/EUserv_extend/

**Comment by ella-tj** [comment]
https://github.com/cokemine/EUserv_extend/，这个试了，不能在腾讯云函数使用，大佬能不能改下代码啊，谢谢啦！

**Comment by o0oo0ooo0** [comment]
> [https://github.com/cokemine/EUserv_extend/，这个试了，不能在腾讯云函数使用，大佬能不能改下代码啊，谢谢啦！](https://github.com/cokemine/EUserv_extend/%EF%BC%8C%E8%BF%99%E4%B8%AA%E8%AF%95%E4%BA%86%EF%BC%8C%E4%B8%8D%E8%83%BD%E5%9C%A8%E8%85%BE%E8%AE%AF%E4%BA%91%E5%87%BD%E6%95%B0%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E4%B8%8D%E8%83%BD%E6%94%B9%E4%B8%8B%E4%BB%A3%E7%A0%81%E5%95%8A%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%95%A6%EF%BC%81)

我就是改它的呀,你本地看看能用不

**Comment by ella-tj** [comment]
想在云函数上使用，比较方便维护。

**Comment by o0oo0ooo0** [comment]
> 想在云函数上使用，比较方便维护。

要等他们修复

**Comment by ella-tj** [comment]
知道了，谢谢大佬。

**Comment by o0oo0ooo0** [comment]
> 知道了，谢谢大佬。

改好了,你看看能用不

**Comment by ella-tj** [comment]
可以用了，谢谢大佬了！！
